### ISSUE TITLE
Module build failed: Error: resolve-url-loader: CSS error

### ISSUE THREAD

**Issue by netdjw** [bholloway/resolve-url-loader#107] opened 2018-10-19 10:22 UTC
Hi,

I have a strange malfunction with resolve-url-loader. I have this webpack.config.js:

```
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');
const path = require('path');

module.exports = {
  entry: ['./src/main.js', './src/main.scss'],
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: 'index.js'
  },
  devtool: "source-map",
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          use: [
            { loader: 'css-loader', options: { minimize: true, sourceMap: true } },
            { loader: 'resolve-url-loader', options: { sourceMap: true } },
            { loader: 'sass-loader', options: { sourceMap: true } },
            
          ]
        })
      },

      {
        test: /\.(jpg|png|gif|ico|svg)$/,
        use: [{
          loader: 'file-loader',
          options: {name: '[name].[ext]', publicPath: 'img/', outputPath: 'img/'}
        }]
      },

      {
        test: /\.html$/,
        use: [
          {
            loader: 'html-loader',
            options: {
              interpolate: true
            }
          }
        ]
      }
    ]
  },
  plugins: [

    new ExtractTextPlugin({ // define where to save the file
      filename: 'style.css',
      allChunks: true,
    }),

    new HtmlWebpackPlugin({
      template: './src/main.html',
      filename: 'index.html'
    }),

    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      "window.jQuery": "jquery"
    })

  ],
};
```

this is the package.json file:

```
{
  "name": "my-project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build:watch": "webpack --watch"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "css-loader": "^1.0.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^2.0.0",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "node-sass": "^4.9.3",
    "resolve-url-loader": "^3.0.0",
    "sass-loader": "^7.1.0",
    "webpack": "^3.9.1"
  },
  "dependencies": {
    "bootstrap": "^4.1.3",
    "jquery": "^3.3.1",
    "owl.carousel": "^2.3.4",
    "popper.js": "^1.14.4"
  }
}
```

In the SCSS file I have this line what is the reason of the problem:

`background-image: url('img/hero-slider-arrow.png');`

I tried to change this line to this one:

`background-image: url('data:image/png;base64,iVBORw0KGgoAAAA...==');`

And in both case I got this error message:

```
ERROR in ./node_modules/css-loader??ref--0-1!./node_modules/resolve-url-loader??ref--0-2!./node_modules/sass-loader/lib/loader.js??ref--0-3!./src/main.scss
    Module build failed: Error: resolve-url-loader: CSS error
      source-map information is not available at url() declaration
      at file://d:\LARAVEL\Code\my-project\src\main.scss:7252:5
        at encodeError (d:\LARAVEL\Code\my-project\node_modules\resolve-url-loader\index.js:218:12)
        at onFailure (d:\LARAVEL\Code\my-project\node_modules\resolve-url-loader\index.js:175:14)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

Doublechecked the image file is on that path what is given. But if I use data:image/png solution... same error message. I don't understand what is the problem.

The other images working fine with similar url('img/filename.png') format.

Any idea?

**Comment by netdjw** [comment] 2018-10-19 11:58
Thanks, I did these things, and nothing userful in debug mode.

I tried to turn off the sourceMap too, it isn't help.

**Comment by netdjw** [comment] 2018-10-19 12:03
And one more thing: I use several background-images in several other files in this project, and those works fine. Those files hasn't any difference (except the file names of course).

I suspect a bug in resolve-url-loader, because this malfunction came out earlier but it was gone. I belived my colleges solved the problem, but now I asked them, and nobody solved it. Simply just gone. Strange.

**Comment by asbjornh** [comment] 2018-10-23 08:41
(Also, downgrading to `2.3.1` solves the issue)

**Comment by bholloway** [comment] 2018-10-23 08:44
> "Simply just gone. Strange."
@netdjw I interpreted this as the problem went away. Is this still a problem with you? Is this a problem with your colleagues?

**Comment by bholloway** [comment] 2018-10-23 09:01
Just reacquainting myself with the code. It looks like _any_ `url()` will require the source-map to be valid at that location. See [this code here](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/lib/engine/postcss.js#L63-L73).

This happens before we look further at the `url()` to see if we want to process it. So that would explain why @netdjw still gets the error with a data URI.

@asbjornh @netdjw I need some more data. Some ideas...
* I'm presuming you're working on closed source. Is there any chance you can construct a minimum failing example, open source?
* Can you try `adjust-sourcemap-loader` with `debug` mode in between `sass-loader` and `resolve-url-loader`. It will display the incoming source-map sources.

My current theory is that there is some upstream problem with the source-map sources. You should look to see it includes all the files you are compiling.

**Comment by asbjornh** [comment] 2018-10-23 09:43
Yeah, I'll see if I get the time to create a minimum example during this week :)

**Comment by asbjornh** [comment] 2018-10-24 18:57
Ok this is quite weird. I've narrowed it down as far as I can I think. This setup fails with the above mentioned error on Windows 10, Node `8.11.4`. The exact same setup builds fine on MacOS.

As you can see in `style.scss` below, there is a `calc` with a line break and extra parentheses inside of it. Remove the line breaks or the parentheses and the build succeeds. This is, of course, a really contrived example, but that calc originally contained some really verbose math. I use VS Code with autoFormat enabled, so a line break was inserted automatically. 

I also tried downgrading to `resolve-url-loader@2.3.1`. The build succeeded (on Windows). The generated `css` file is at the very bottom of this post. Also, removing `resolve-url-loader` altogether makes the build succeed. When building without `resolve-url-loader`, the resulting css file is identical to the one with `resolve-url-loader@2.3.1` in the build pipeline.

webpack.config.js
```
/* eslint-env node */
/* eslint-disable no-console */
const path = require("path");
const ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = () => {
  return {
    devtool: "source-map",
    entry: { style: "./style.scss" },
    output: {
      path: path.resolve(__dirname, "dist")
    },
    module: {
      rules: [
        {
          test: /\.scss$/,
          exclude: /node_modules/,
          use: ExtractTextPlugin.extract([
            {
              loader: "css-loader",
              options: {
                importLoaders: 1,
                sourceMap: true
              }
            },
            { loader: "resolve-url-loader", options: { sourceMap: true } },
            { loader: "adjust-sourcemap-loader", options: { debug: true } },
            { loader: "sass-loader", options: { sourceMap: true } }
          ])
        },
        {
          test: /\.svg$/,
          use: { loader: "file-loader" }
        }
      ]
    },
    plugins: [new ExtractTextPlugin("[name].[chunkhash].css")]
  };
};
```

package.json
```
{
  "name": "example",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "build": "webpack --mode=production"
  },
  "dependencies": {
    "adjust-sourcemap-loader": "^1.2.0",
    "css-loader": "^1.0.0",
    "extract-text-webpack-plugin": "4.0.0-beta.0",
    "file-loader": "^2.0.0",
    "node-sass": "^4.5.1",
    "resolve-url-loader": "^3.0.0",
    "sass-loader": "^7.1.0",
    "webpack": "^4.22.0",
    "webpack-cli": "^3.1.2"
  }
}
```

style.scss
```
body {
  font-size: calc(
    (1px)
  );
  background-image: url(./image.svg);
}
```

Shell output:
```
adjust-sourcemap-loader:
  ##path##\style.scss
        @ ##path##\node_modules\sass-loader\lib\loader.js??ref--4-4
    INPUT style.scss
 ABSOLUTE ##path##\style.scss

adjust-sourcemap-loader:
  ##path##\style.scss
        @ ##path##\node_modules\sass-loader\lib\loader.js?{"sourceMap":true}
    INPUT style.scss
 ABSOLUTE ##path##\style.scss
Hash: c18a8a717939eec50edc
Version: webpack 4.22.0
Time: 616ms
Built at: 2018-10-24 20:15:21
 2 assets
Entrypoint style = style.js style.js.map
[0] ./style.scss 1.69 KiB [built] [failed] [1 error]

ERROR in ./style.scss
Module build failed (from ./node_modules/extract-text-webpack-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration
  at file://##path##\style.scss:4:3
    at encodeError (##path##\node_modules\resolve-url-loader\index.js:218:12)
    at onFailure (##path##\node_modules\resolve-url-loader\index.js:175:14)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at runLoaders (##path##\node_modules\webpack\lib\NormalModule.js:286:20)
    at ##path##\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at ##path##\node_modules\loader-runner\lib\LoaderRunner.js:230:18
    at context.callback (##path##\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at onFailure (##path##\node_modules\resolve-url-loader\index.js:175:5)
    at <anonymous>
    at runMicrotasksCallback (internal/process/next_tick.js:121:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./style.scss
```


Generated css file with `resolve-url-loader@2.3.1`. The url points to the correct svg file in the build folder.
```
body {
  font-size: calc(
 (1px));
  background-image: url(7b56e1eab00ec8000da9331a4888cb35.svg);
}


/*# sourceMappingURL=style.9e5ee3d7a184f4b00938.css.map*/
```

**Comment by bholloway** [comment] 2018-10-25 00:31
This is some really good work @asbjornh!

The `resolve-url-loader@2.3.1` uses `rework` engine. So maybe also try `resolve-url-loader@3.0.0` with `engine:rework`. That downgrades you from `postcss` back to `rework` but keeps the newly refactored/tested code.

🤔I guess the sources look normal. I suspect something to do with the different line break characters in Windows, `CR` and `LF` together unless I am mistaken.

I am wondering if @netdjw can point to similar code. Is the same problem you both have or 2 different problems.

For my part I will create a test case for this as soon as I get some time. In the mean time please let me know if the engine-only downgrade helps you for now.

**Comment by asbjornh** [comment] 2018-10-25 08:15
Yep! `engine: "rework"` also solves this! :)

**Comment by bholloway** [comment] 2018-10-26 01:19
@asbjornh as an outside chance take a look at the [linefeed option](https://github.com/sass/node-sass#linefeed--v300) in node-sass. You should be able to set this in `sass-loader` options.

**Comment by bholloway** [comment] 2018-10-26 01:31
Looking at `postcss` [tokenizer](https://github.com/postcss/postcss/blob/master/lib/tokenize.es6#L64-L88), it looks to me that `CRLF` (windows) would result in two line breaks instead of one.

But how this would make the source-map unusable I am unsure. 🤔

**Comment by ZebraFlesh** [comment] 2018-12-15 01:35
I'm also encountering this issue on Windows:
OS: Windows 10
node: 10.13.0
webpack: 4.27.1
resolve-url-loader: 3.0.0

The `engine: 'rework'` option did resolve the issue, but passing `linefeed: 'crlf'` to sass-loader did not.  I have an .scss file that contains a number of subsetted font definitions (regular, bold, and italic faces for each of a variety of subsets such as latin/latin-extended/cyrillic/greek/etc). The troublesome file is of this form:

```
@import '../variables';

/* stylelint-disable function-url-quotes, font-family-name-quotes */

@function get-type-path($filename) {
    @return $type-path + $filename;
}

$latin-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC,
    U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
$latin-ext-range: U+0100-024F, U+1E00-1EFF, U+20A0-20AB, U+20AD-20CF,
    U+2C60-2C7F, U+A720-A7FF;
$cyrillic-range: U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116;
$greek-range: U+0370-03FF;

// greek
@font-face {
    font-family: 'Lato';
    font-style: italic;
    font-weight: 400;
    src: local('Lato Italic'), local('Lato-Italic'),
        url(get-type-path('lato-italic-greek.woff2')) format('woff2');
    unicode-range: U+0370-03FF;
    text-rendering: optimizeLegibility;
}
// 23 similar @font-face definitions
```

Removing the line break from the `src` line doesn't seem to have any impact: resolve-url-loader still produces the same error, the same as originally reported:

```
    ERROR in ./src/baseStyle/_font-family.scss
    Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
    ModuleBuildError: Module build failed (from ./node_modules/resolve-url-loader/index.js):
    Error: resolve-url-loader: CSS error
      source-map information is not available at url() declaration
      at file://C:\Users\NOPE\myproject\src\baseStyle\_font-family.scss:65:3
        at encodeError (C:\Users\NOPE\myproject\node_modules\resolve-url-loader\index.js:218:12)
        at onFailure (C:\Users\NOPE\myproject\node_modules\resolve-url-loader\index.js:175:14)
        at runLoaders (C:\Users\NOPE\myproject\node_modules\webpack\lib\NormalModule.js:301:20)
        at C:\Users\NOPE\myproject\node_modules\loader-runner\lib\LoaderRunner.js:364:11
        at C:\Users\NOPE\myproject\node_modules\loader-runner\lib\LoaderRunner.js:230:18
        at context.callback (C:\Users\NOPE\myproject\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at onFailure (C:\Users\NOPE\myproject\node_modules\resolve-url-loader\index.js:175:5)
     @ ./src/baseStyle/index.js 9:0-29
     @ ./src/components/type/headers/SectionHeader.js
     @ ./demo/src/components/IconDemo.js
     @ ./demo/src/routes.js
     @ ./demo/src/mount.js
```

The contes of src/baseStyle/index.js are straight forward:
```
import './_normalize.scss';
import './_font-family.scss';
import './_base.scss';
import '../components/type/typography.scss';
```

**Comment by bholloway** [comment] 2018-12-15 03:07
@ZebraFlesh If you can setup a minimum breaking example repo then I can devote some time to debugging.

Earlier I tried to create a test case but I could not reproduce the problem on windows.

**Comment by michaelbeaumont** [comment] 2019-02-04 09:40
I had this issue as well, the following change fixed it:

```
 .helpdesk-header {
   position: relative;
   width: 100%;
-  height: 450px;
   background-image: url('~alias/image.jpg');
   background-size: 100% auto;
+  height: 450px;
   text-align: center;
   .helpdesk-container {
```

Sorry, I don't have time at the moment for a minimal repo!

**Comment by lf-jeremy** [comment] 2019-02-07 19:06
Passing `linefeed: "crlf"` to `node-sass` fixed this issue for my team members using `resolve-url-loader@3.0.0` under Windows (same issue not present for us on OSX or Linux).

**Comment by michaelbeaumont** [comment] 2019-02-12 11:12
Changing `linefeed` with `sass-loader` did not work for us.
I have a single SCSS file (explicitly showing `crlf` endings):

```
.planner-workspace-label {^M
   transition: width .3s ease, width .3s ease,^M
          left 200ms,^M
          background-color 0.2s ease;  ^M
   background-image: url('~alias/image.png');^M
}^M
```

When `postcss` and `resolve-url-loader/lib/engine/postcss.js` see this content, after it's been through `sass-loader`, `resolve-url-loader` chokes on the following declaration:

```
  "declaration": {
    ...,
    "source": {
      "start": {
        "line": 5,
        "column": 3
      },
      "input": {
        "css": ".planner-workspace-label {\r\n  transition: width .3s ease, width .3s ease,\r left 200ms,\r background-color 0.2s ease;\r\n  background-image: url(\"~alias/image.png\"); }\r\n",
     },
     value: "url(\"~alias/image.png\")"
     ...
```

Note the 2 `\r` carriage returns not accompanied by a newline in the input.

Unfortunately, `params.sourceMapConsumer` doesn't contain any mapping with `generatedLine = 5`, only until `generatedLine = 3` and so we throw the error.

The `postcss` tokenizer correctly? recognizes a single `\r` as a line break, the generated mappings seem not to however.

**Comment by bholloway** [comment] 2019-02-16 08:50
@michaelbeaumont I would not expect to see naked `\r` in a file using `\r\n` scheme, but I put that down to my ignorance. What platform/editor are you using?

**Comment by michaelbeaumont** [comment] 2019-02-16 12:10
There are no naked `\r` characters in the file initially, the file contains only normal `\r\n` sequences (the initial snippet I posted, where `^M` = `\r`).
The naked `\r`s appear to be from `libsass`, because running the file manually through `node-sass` manually also produces this output, where the `\r\n` pairs inside the CSS values (after the commas), i.e lines 2 and 3 are reduced to `\r`.

I might be overlooking something obvious, but it seems very much like a `libsass` issue.

Anyway, I stopped investigating further because this led me to the fix (for this specific case at least) of just removing the line breaks after the commas.

**Comment by bholloway** [comment] 2019-02-16 23:27
Sorry @michaelbeaumont I see now that you did originally say that.
> "It appears this is `libsass`'s doing."

**Comment by bholloway** [comment] 2019-02-16 23:28
**To summarise**

There is some issue with multiline declarations.
* @netdjw originally implied a problem with base64 data URI.
* @asbjornh shows line-break and/or parenthesis imply a problem.
* @michaelbeaumont shows a possible sensitivity to preceding declarations.
* Simplifying the declaration (removing the line breaks or parenthesis) worked for @asbjornh @michaelbeaumont but does _not_ work for @ZebraFlesh.
* Changing node-sass `linefeed` option worked for @lf-jeremy but did _not_ work for @ZebraFlesh @michaelbeaumont.
* @michaelbeaumont shows that naked `\r` coming from `libsass`.

**The workarounds**
* @netdjw is no longer experiencing the problem but did _not_ actively fix it.
* @ZebraFlesh @asbjornh has downgraded to `engine: rework`. 
* @lf-jeremy is using the `linefeed` option by way of `sass-loader`.

**Remaining**
* **bugfix** Unable to reproduce - Waiting for minimum breaking example.
* **enhancement** Think about an architecture change [here](https://github.com/bholloway/resolve-url-loader/blob/master/packages/resolve-url-loader/lib/engine/postcss.js#L63-L73) such that unprocessed statements don't require source-map. This is not a fix.

**Comment by bholloway** [comment] 2019-02-17 04:17
I've synthesised an orphan CR in tests and it (correctly) fails in both MacOS and Windows.

That has allowed me to draft a possible fix in #108.

I won't publish this pre-release because really I am not sure we are on the right track. It remains to be see that this fixes the actual problem.

So please install `bholloway/resolve-url-loader#remove-orphan-CR-character` and let me know.

**Comment by bholloway** [comment] 2019-02-22 13:07
^^ @michaelbeaumont (et. al) have you had a chance to test this possible fix?

**Comment by asbjornh** [comment] 2019-02-23 16:38
It's been a while so I no longer remember where to find the original problem :P I'll see if I have time on monday to test this with my test case above :)

**Comment by asbjornh** [comment] 2019-02-25 13:48
@bholloway 
I tried installing from that branch now, but since the actual npm package resides in a subdirectory it can't be installed from github. Could you publish a tagged version to npm?

**Comment by moek** [comment] 2019-02-25 14:23
I could not install the branch of the package either:

    npm i -D "@bholloway/resolve-url-loader.git#remove-orphan-CR-character"

It returns

    Could not install from "@bholloway/resolve-url-loader.git#remove-orphan-CR-character" as it does not contain a package.json file.

**Comment by bholloway** [comment] 2019-02-25 20:24
oops sorry. of course.

try `resolve-url-loader@next` which points to `resolve-url-loader@3.1.0-beta.1`.

**Comment by asbjornh** [comment] 2019-02-26 10:57
`3.1.0-beta.1` crashes on windows without options with my example repo above. With `removeCR: true` it builds fine :) Maybe `removeCR` should default to `true`? Like, shouldn't the default behaviour be that the loader is a little bit less crashy rather than more?

**Comment by denisoster** [comment] 2019-02-26 18:41
@bholloway  To solve
`Module build failed: Error: resolve-url-loader: CSS error`
`source-map information is not available at url() declaration`

I rollback to version `2.3.2`

**Comment by bholloway** [comment] 2019-02-28 11:53
> "I rollback to version `2.3.2`"

@denisoster Version `2` is no longer supported. Try Version `3` with `engine: rework` which is equivalent. There has been nothing to suggest that this is a problem with `rework`. But `rework` will choke on modern CSS.

> "`3.1.0-beta.1` crashes on windows without option"

@asbjornh I take "crashes" to mean the original error that @denisoster repeated just above (?).

It seems like there are a few people here on this issue with similar/same problem. However I can't reproduce on windows. We've established there is badly formed input with orphan `CR`. So I'm guessing some some upstream bug in the CSS loader chain. We have no minimum breaking example.

I'm looking to make this opt-in. 
* I'm happy to patch upstream bugs to make this loader work, but not by default.
* I'd hope the upstream bug would be eventually fixed and this option redundant.
* This fix might hurt other users without this edge case.

If this fix helps you @asbjornh then I'll release as `3.1.0`.

**Comment by bholloway** [comment] 2019-02-28 11:58
^ @denisoster Your linked issue is unrelated to this one. Bumping you to a new issue.

**Comment by asbjornh** [comment] 2019-02-28 12:14
@bholloway Yeah I see your point. I’m thinking more as a consumer of the package. As a consumer I don’t know or care about the upstream, so to me there is an option to make the loader not crash in some cases on windows, and why would I ever want to disable that? :) Like `crashSometimesOnWindows: true` by default to make an extreme example 😛 But like I said you have valid points.

About the lack of a minimal breaking example, were you not able to use mine from above? If github corrected the white space I’d be happy to share the files some other way (because they are consistently not building in my local copy)

**Comment by asbjornh** [comment] 2019-02-28 12:15
Oh and yes, the option fixes the issue for me. But the rework engine also does that and I’ve added that for all my codebases so to me it doesn’t really matter that much which option I set to make it build :)

**Comment by bholloway** [comment] 2019-02-28 12:36
@asbjornh I couldn't get your example `scss` to fail (with the `calc` that is) but I confess I didn't fully set it up, I just put it in an e2e test case.

Sorry I should have said "minimum failing repo". I'm a bit blind to people dumping their file contents into the posts, they are always incomplete and I just don't have time to setup. But I'll try to get time to set up yours.

That said, from @michaelbeaumont analysis I was able to explicitly add some orphan CR. The `calc` then failed in both MacOS and Windows.

The e2e test case is (template string)
```
.some-class-name {
  font-size: calc(${'\r'}
    (1px)${'\r'}
  );
  background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==);
}
```

My experiment with functional programming the tests is a bit unintelligible but you can see it [here](https://github.com/bholloway/resolve-url-loader/blob/remove-orphan-CR-character/test/cases/orphan-carriage-return.postcss.js#L34-L39).

The dependencies I'm testing against are [here](https://github.com/bholloway/resolve-url-loader/tree/remove-orphan-CR-character/packages/resolve-url-loader/test).

I haven't heard anyone screaming for this release so I might
* Add more info to the readme in #117 
* Try to get your example to fail exactly as you posted and see if anything changes

**Comment by asbjornh** [comment] 2019-02-28 13:51
Oh, sorry! I'll put the things in a repo asap

**Comment by asbjornh** [comment] 2019-02-28 13:58
@bholloway https://github.com/asbjornh/resolve-url-loader-breaking-example

**Comment by michaelbeaumont** [comment] 2019-02-28 15:14
@bholloway  The fix worked for me, thanks a lot for investing so much time! Before I posted, I searched for the bug in libsass for a little while, unfortunately no luck. But it's certainly a bug somewhere upstream, so I agree with the `removeCR` default being `false`.

**Comment by lf-jeremy** [comment] 2019-03-04 16:29
@bholloway -  this is the result we had with our project:

- removed the `linefeed: "crlf"` option from `sass-loader`
- switched to `resolve-url-loader@3.1.0-beta.1`

As expected: `Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found orphan CR, try removeCR option)`

After adding `removeCR: true`, the build was green. 👍 

To help track down the issue some more, we reverted back to version `3.0.1` without specifying any linefeed option for `sass-loader` so we could cause the error to come back. Our `resolve-url-loader` options are:

```javascript
options: {
  sourceMap: true,
  attempts: 1,
}
```

We are also using `url-loader` with the following options:

```javascript
options: {
  limit: 2048,
  emitFile: true,
  outputPath: 'resources/',
}
```

This issue was present in a project with only a few first-party `url(` stylesheet references to local/relative files:
- 2 png files above the url-loader inlining threshold
- 1 eot file that got inlined without issues
- 1 svg file below the url-loader inlining threshold that caused the build to fail with the `source-map information is not available at url() declaration` error

It seemed like the inlining process may have been related, but this started to lead away from that possibility.

We swapped the failing svg reference to a larger svg above the inlining threshold and located in the same directory, and the same error persisted.

All of our `url(` references are on declarations that are on a single line.

Here is the chain of loaders in play:

the loader from `mini-css-extract-plugin`, `css-loader`, `postcss-loader`, `resolve-url-loader`, `sass-loader`

Other relevant webpack plugins:
- stylelint-webpack-plugin

**Comment by laTruffe79** [comment] 2019-03-21 09:27
Hello, could you explain where did you add removeCR: true and where are the resolve-url-loader options ? in ./node_modules/resolve-url-loader/package.json ? Thanks for your help .

**Comment by asbjornh** [comment] 2019-03-21 10:51
In webpack.config:

```js
{ loader: 'resolve-url-loader', options: { removeCR: true } }
```

**Comment by bholloway** [comment] 2019-03-21 21:07
Sorry been completely slammed with work. Have not yet investigated further the root cause.

Please let me know if this is immediately needed. Otherwise I’ll stick to the plan above.

**Comment by laTruffe79** [comment] 2019-03-21 22:31
I've been forced to rollback to version 2.0.2, maybe it's a dependency
problem with laravel-mix 4.0.15 ?

Le jeu. 21 mars 2019 à 22:07, Ben Holloway <notifications@github.com> a
écrit :

**Comment by bholloway** [comment] 2019-04-03 10:32
I moved the breaking example to [resolve-url-loader-107](https://github.com/bholloway/resolve-url-loader-107).

The `style.scss` was committed to the repo with `CRLF` but I think that is incidental.

As promised by @asbjornh this _does_ pass in MacOS and fail in Windows (for me).

**Analysis**

On checkout in windows it appears with `CRLF` only (`0D0A`).

```
> Format-Hex style.scss

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   62 6F 64 79 20 7B 0D 0A 20 20 66 6F 6E 74 2D 73  body {..  font-s
00000010   69 7A 65 3A 20 63 61 6C 63 28 0D 0A 20 20 20 20  ize: calc(..
00000020   28 31 70 78 29 0D 0A 20 20 29 3B 0D 0A 20 20 62  (1px)..  );..  b
00000030   61 63 6B 67 72 6F 75 6E 64 2D 69 6D 61 67 65 3A  ackground-image:
00000040   20 75 72 6C 28 2E 2F 69 6D 61 67 65 2E 73 76 67   url(./image.svg
00000050   29 3B 0D 0A 7D                                   );..}
```

Running stand alone sass compile.
```
> npx node-sass style.scss output.css
```

Interestingly the line feeds come out as LF (`0A`).  But we do get the orphan CR (`0D`) we're looking for.

```
> Format-Hex output.css

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   62 6F 64 79 20 7B 0A 20 20 66 6F 6E 74 2D 73 69  body {.  font-si
00000010   7A 65 3A 20 63 61 6C 63 28 0D 20 28 31 70 78 29  ze: calc(. (1px)
00000020   29 3B 0A 20 20 62 61 63 6B 67 72 6F 75 6E 64 2D  );.  background-
00000030   69 6D 61 67 65 3A 20 75 72 6C 28 2E 2F 69 6D 61  image: url(./ima
00000040   67 65 2E 73 76 67 29 3B 20 7D 0A                 ge.svg); }.
```

With appropriate settings for linefeed.
```
> npx node-sass --linefeed crlf style.scss output.css
```

The line feeds come out as CRLF (`0D0A`).  But we _still_ get the orphan CR (`0D`) we're looking for.

```
> Format-Hex output.css

           00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

00000000   62 6F 64 79 20 7B 0D 0A 20 20 66 6F 6E 74 2D 73  body {..  font-s
00000010   69 7A 65 3A 20 63 61 6C 63 28 0D 20 28 31 70 78  ize: calc(. (1px
00000020   29 29 3B 0D 0A 20 20 62 61 63 6B 67 72 6F 75 6E  ));..  backgroun
00000030   64 2D 69 6D 61 67 65 3A 20 75 72 6C 28 2E 2F 69  d-image: url(./i
00000040   6D 61 67 65 2E 73 76 67 29 3B 20 7D 0D 0A        mage.svg); }..
```

**Conclusion**

Certainly looks to be a bug in SASS. Sure the example breaks in webpack but the root cause is reproducible in `node-sass` CLI.

But this is simply reproducing the excellent work of others above.

**Comment by bholloway** [comment] 2019-04-03 22:30
So the `removeCR` option is released as `resolve-url-loader@3.1.0`. Thanks to everyone who tested the beta.

The `libsass` bug is apparently fixed `master` as of a few days ago. At some time we will see a `node-sass` release. But I think we will keep this `removeCR` option, at least until the next major release.

Sorry for the delay. Its been a pleasure working with you all on this.

**Closed by bholloway** 2019-04-03 22:30 UTC
Labels: possible fix needs community testing

**Comment by fiskhandlarn** [comment] 2019-04-05 11:12
Can someone please help me how to add the option `removeCR` when using `import-glob-loader`? Current rule in my `webpack.mix.js`:

```
      {
        test: /\.scss$/,
        loader: 'import-glob-loader',
      },
```

@asbjornh you [mentioned](https://github.com/bholloway/resolve-url-loader/issues/107#issuecomment-432148139) `import-glob` ..?

**Comment by fiskhandlarn** [comment] 2019-05-27 08:00
Anyone? Pls help X)
@asbjornh

**Comment by asbjornh** [comment] 2019-05-27 14:50
Dude, just read the comments... Already answered

**Comment by fiskhandlarn** [comment] 2019-05-28 06:59
@asbjornh DUDE, the comments does NOT answer my question about using `import-glob-loader`. I wouldn't ask if it worked, would I?

**Comment by bholloway** [comment] 2019-05-28 07:15
Okay lets discuss on #125 and keep this particular issue **closed**.

**Comment by erwinfriasmtz** [comment] 2019-06-03 15:42
I had the same probleme with resolve-url-loader: CSS error and I found the fix adding removeCR and sourceMap:

`          {
            loader: 'resolve-url-loader',
            options: {
              removeCR: true,
              sourceMap: true
            }
          }`

**Comment by esynaps** [comment] 2019-08-12 09:20
With Webpack Encore :

```
    .enableSassLoader((options) => {}, {
        resolveUrlLoaderOptions: {
            removeCR: true
        }
    })
```

**Comment by zehawki** [comment] 2019-10-31 15:43
This is not to open this issue, but just to document my findings. I also hit this issue after doing a yarn upgrade. To resolve, I used the excellent instructions given here: https://npm.runkit.com/resolve-url-loader

> Diagnosis
> 
> Run a stand-alone sass build npx node-sass index.scss output.css
> Use a hex editor to check line endings Format-Hex output.css (I used the superb https://hexed.it/ie.html)
> Expect 0DOA (or desired) line endings. Single 0D confirms this problem.

My output CSS of 11K LOC threw up 27 instances of 0D. Here are all the culprits:

`      .nav-search__result {
        /*  max-width: 320px; // padding: 7px;
                float: left;
                position: absolute;
                right: 80%;
                top: 44px;
                background-color: #fff;
                width: 100%; */ } }`

`/*.home_anim {
    transition: opacity 0.5s;
    opacity: 1;
}

.home_anime.hide {
    opacity: 0;
    pointer-events: none;
}*/`

`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen,
 Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif;`

**Comment by barbala4o** [comment] 2020-09-15 07:51
> I had the same probleme with resolve-url-loader: CSS error and I found the fix adding removeCR and sourceMap:
> 
> ` { loader: 'resolve-url-loader', options: { removeCR: true, sourceMap: true } }`

where did you add these lines exactly??

**Comment by dospuntocero** [comment] 2020-12-14 23:48
same question... just wondering where you add that

**Comment by erwinfriasmtz** [comment] 2020-12-15 19:40
Hi guys! 

You should add this way in your css rules into webpack.config.js file

`      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          'style-loader',
          MiniCssExtractPlugin.loader,
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              autoprefixer: { browser: ['last 2 versions'] },
              sourceMap: true,
              plugins: () => [ autoprefixer ]
            }
          },
          {
            loader: 'resolve-url-loader',
            options: {
              removeCR: true,
              sourceMap: true
            }
          },
          'sass-loader?outputStyle=compressed&sourceMap'
        ]
      `

**Comment by M-Matin-dev** [comment] 2021-01-05 07:57
See [this post on stackoverflow](https://stackoverflow.com/questions/58649677/node-error-resolve-url-loader-css-error) it helped me.

> same question... just wondering where you add that

**Comment by hmawla** [comment] 2021-06-01 13:32
Well...
Just pointing to the existence of this package:
https://www.npmjs.com/package/resolve-url-loader-with-removecr

**Comment by ZebraFlesh** [comment] 2021-06-01 14:15
> Well...
> Just pointing to the existence of this package:
> https://www.npmjs.com/package/resolve-url-loader-with-removecr

1. I have no idea where the source code is for that module, since the info in the NPM registry points back to this package.
2. The 3.1 release of this package included the `removeCR` option: https://github.com/bholloway/resolve-url-loader/blob/v4-maintenance/packages/resolve-url-loader/docs/troubleshooting.md#windows-line-breaks

**Comment by bholloway** [comment] 2021-06-01 22:01
Furthermore in `resolve-url-loader@4` the `removeCR` option is activated by default on windows OS now.

So there should not be a use case for `resolve-url-loader-with-removecr`.

**Comment by Johnoris** [comment] 2022-09-16 08:53
I had the same issue I just uninstalled node-sass and installed sass instead and it now works fine
