### ISSUE TITLE
webpack 2.1.0-beta23+ breaks loader.options.output.path

### ISSUE THREAD

**Issue by manofearth** [bholloway/resolve-url-loader#36] opened 2016-10-19 08:53 UTC
After I applied this patch: https://github.com/jtangelder/sass-loader/pull/290

I have an error

```
ERROR in ./~/css-loader?sourceMap!./~/resolve-url-loader!./~/sass-loader?sourceMap!./angular/app/app.style.scss
Module build failed: TypeError: Cannot read property 'path' of undefined
    at Object.resolveUrlLoader (C:\www\vast\node_modules\resolve-url-loader\index.js:38:47)
```

My loader config:

```
{
   test:    /\.(sass|scss)$/,
   loaders: ['css-to-string-loader', 'css-loader?sourceMap', 'resolve-url', 'sass-loader?sourceMap']
},
```

Webpack version: 2.1.0-beta.25

**Comment by bholloway** [comment] 2016-10-19 09:26
I believe this is a duplicate of #33.

Refer to [this workaround](https://github.com/bholloway/resolve-url-loader/issues/33#issuecomment-249830601).

**Comment by manofearth** [comment] 2016-10-20 03:30
Thank you for workaround, it helped. But I think this is a problem, and it makes sense to leave this issue opened.

**Comment by vladimiry** [comment] 2016-10-21 19:55
Doesn't look for me as duplicate since that issues is closed and no proper fix implemented.

It's not recommended to use `webpack.LoaderOptionsPlugin` thing (Webpack 2. supports `loader.options` as an object, not like before when `query` was always a string), a bad practice, but it's helpful for a gradual transition to Webpack 2.

So using `LoaderOptionsPlugin` is workaround, a temporary solution, proper fix would imply a Webpack 2 support. So please keep this issue opened.

**Comment by bholloway** [comment] 2017-02-14 05:36
@manofearth @vladimiry could you please let me know if #45 will fix your issue.

Use `npm i resolve-url-loader@bholloway/resolve-url-loader#feature/support-sass-loader-6`

**Closed** 2017-02-16 06:48 UTC
Labels: Webpack2
